version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: RentalSystem
      POSTGRES_PASSWORD: rentalcar
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: lihao.wei23@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rentalcar
    ports:
      - 127.0.0.1:8080:80


      